Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2021-12, with the labels that each got.

#797 Paddle: add a little randomization in the dy speed
  src/displayapp/screens/Paddle.cpp
Labels: enhancement, hacktoberfest-accepted

#756 BLE FS Using adafruits Simple (not fast) BLE FS Api
  src/CMakeLists.txt
  src/components/ble/FSService.cpp
  src/components/ble/FSService.h
  src/components/ble/NimbleController.cpp
  src/components/ble/NimbleController.h
  src/components/fs/FS.cpp
  src/components/fs/FS.h
  src/systemtask/Messages.h
  src/systemtask/SystemTask.cpp
Labels: enhancement, question/discussion, feature request

#718 Integrate color picker into PineTimeStyle watchface
  src/CMakeLists.txt
  src/displayapp/Apps.h
  src/displayapp/DisplayApp.cpp
  src/displayapp/screens/Clock.cpp
  src/displayapp/screens/Clock.h
  src/displayapp/screens/PineTimeStyle.cpp
  src/displayapp/screens/PineTimeStyle.h
  src/displayapp/screens/settings/SettingPineTimeStyle.cpp
  src/displayapp/screens/settings/SettingPineTimeStyle.h
  src/displayapp/screens/settings/Settings.cpp
Labels: enhancement, feature request
