Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2021-10, with the labels that each got.

#692 Fix the size of the filesystem.
  src/components/fs/FS.h
Labels: bug

#705 Issue templates to tame the wilderness
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/feature-request.yaml
Labels: documentation, enhancement, needs more info, needs more work, untested

#793 Exclude some clang-tidy checks
  .clang-tidy
Labels: hacktoberfest-accepted

#784 Correctly Define DFU
  doc/gettingStarted/gettingStarted-1.0.md
Labels: documentation, hacktoberfest-accepted
