Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2021-05, with the labels that each got.

#275 Changed text in Navigation
  src/displayapp/screens/Navigation.cpp
Labels: question

#354 Notification title fix
  src/displayapp/screens/Notifications.cpp
Labels: enhancement

#347 Feature: Store and show git short ref on PineTime alongside other firmware information
  CMakeLists.txt
  docker/.gitpod.Dockerfile
  docker/Dockerfile
  src/Version.h.in
  src/displayapp/screens/FirmwareValidation.cpp
  src/displayapp/screens/FirmwareValidation.h
  src/displayapp/screens/SystemInfo.cpp
Labels: enhancement

#320 Emit event on power-present toggle
  src/components/battery/BatteryController.cpp
  src/main.cpp
  src/systemtask/SystemTask.cpp
  src/systemtask/SystemTask.h
Labels: need more work
