Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2022-09, with the labels that each got.

#1310 Updated Apps documentation
  doc/code/Apps.md
Labels: documentation

#1344 AlarmController: add const to SecondsToAlarm() function
  src/components/alarm/AlarmController.cpp
  src/components/alarm/AlarmController.h
Labels: enhancement

#1024 Infineat Watchface
  src/CMakeLists.txt
  src/components/datetime/DateTimeController.cpp
  src/components/datetime/DateTimeController.h
  src/components/settings/Settings.h
  src/displayapp/DisplayApp.cpp
  src/displayapp/DisplayApp.h
  src/displayapp/DisplayAppRecovery.cpp
  src/displayapp/DisplayAppRecovery.h
  src/displayapp/screens/CheckboxList.cpp
  src/displayapp/screens/CheckboxList.h
  src/displayapp/screens/Clock.cpp
  src/displayapp/screens/Clock.h
  src/displayapp/screens/WatchFaceInfineat.cpp
  src/displayapp/screens/WatchFaceInfineat.h
  src/displayapp/screens/settings/SettingWatchFace.cpp
  src/displayapp/screens/settings/SettingWatchFace.h
  src/main.cpp
  src/resources/fonts.json
  src/resources/images.json
Labels: new watchface
