Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2023-03, with the labels that each got.

#1658 branches: Update files to refer to main instead of develop
  .devcontainer/README.md
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/issue-report.yaml
  .github/workflows/docker.yml
  .github/workflows/format.yml
  .github/workflows/main.yml
  .github/workflows/pr-comment.yml
  CONTRIBUTING.md
  doc/ExternalResources.md
  doc/MemoryAnalysis.md
  doc/branches.md
  doc/buildAndProgram.md
  doc/versioning.md
Labels: documentation, maintenance

#1669 Fix double tap behaviour on PineTimeStyle settings screen
  src/displayapp/screens/WatchFacePineTimeStyle.cpp
Labels: bug

#1707 pr-comment: Comment instructions instead of failing
  .github/workflows/pr-comment.yml
Labels: maintenance
