Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2023-11, with the labels that each got.

#1752 Update Apps.md
  doc/code/Apps.md
Labels: documentation

#1911 Fix deadlock when a lot of notifications are received in a very short time span
  src/displayapp/DisplayApp.cpp
Labels: bug

#1922 apps: Restore app list order
  src/displayapp/Apps.h
Labels: UI/UX
