Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2023-02, with the labels that each got.

#1561 Update Stopwatch UI *new*
  src/displayapp/InfiniTimeTheme.h
  src/displayapp/screens/StopWatch.cpp
  src/displayapp/screens/StopWatch.h
Labels: enhancement

#1507 Update steps UI
  src/displayapp/screens/Steps.cpp
Labels: enhancement

#1581 Add WatchMate to the list of companion apps
  README.md
Labels: documentation

#1570 Update contributing doc
  doc/contribute.md
Labels: documentation

#1575 Update setsteps UI
  src/displayapp/screens/settings/SettingSteps.cpp
Labels: UI/UX

#1586 Fix Link in buildWithVScode
  doc/buildWithVScode.md
Labels: documentation

#1584 docs: Limit number of jobs used for compilation
  doc/buildAndProgram.md
Labels: documentation

#1633 TimerController: Use chrono for durations
  src/components/timer/TimerController.cpp
  src/components/timer/TimerController.h
  src/displayapp/screens/Timer.cpp
Labels: maintenance

#1638 LittleVgl: Remove unused Cst816S reference
  src/displayapp/DummyLittleVgl.h
  src/displayapp/LittleVgl.cpp
  src/displayapp/LittleVgl.h
  src/main.cpp
Labels: maintenance

#1622 libs: Disable clang-format and -tidy
  src/libs/.clang-format
  src/libs/.clang-tidy
Labels: maintenance

#1642 CONTRIBUTING: Fix broken links
  CONTRIBUTING.md
Labels: documentation

#1636 watchdog: Replace WatchdogView with const Watchdog
  src/displayapp/DisplayApp.cpp
  src/displayapp/DisplayApp.h
  src/displayapp/DisplayAppRecovery.cpp
  src/displayapp/DisplayAppRecovery.h
  src/displayapp/screens/SystemInfo.cpp
  src/displayapp/screens/SystemInfo.h
  src/drivers/Watchdog.h
  src/main.cpp
Labels: maintenance

#1641 LittleVgl: Instantiate in DisplayApp
  src/displayapp/DisplayApp.cpp
  src/displayapp/DisplayApp.h
  src/displayapp/DisplayAppRecovery.cpp
  src/displayapp/DisplayAppRecovery.h
  src/displayapp/DummyLittleVgl.h
  src/main.cpp
  src/systemtask/SystemTask.cpp
  src/systemtask/SystemTask.h
Labels: maintenance

#1640 SystemTask: Move lcd to DisplayApp
  src/displayapp/DisplayApp.cpp
  src/main.cpp
  src/systemtask/SystemTask.cpp
  src/systemtask/SystemTask.h
Labels: maintenance

#1639 DateTimeController: Remove SetTime tick parameter
  src/components/ble/CurrentTimeClient.cpp
  src/components/ble/CurrentTimeService.cpp
  src/components/ble/NimbleController.cpp
  src/components/datetime/DateTimeController.cpp
  src/components/datetime/DateTimeController.h
  src/displayapp/screens/settings/SettingSetDate.cpp
  src/displayapp/screens/settings/SettingSetTime.cpp
  src/main.cpp
Labels: maintenance

#1634 DateTimeController: Use std::tm for storing date
  src/components/datetime/DateTimeController.cpp
  src/components/datetime/DateTimeController.h
Labels: maintenance

#1645 DateTimeController: Fix integer overflow on day of year
  src/components/datetime/DateTimeController.h
Labels: bug

#1566 infineat: Create colors at compile time.
  src/displayapp/screens/WatchFaceInfineat.cpp
  src/displayapp/screens/WatchFaceInfineat.h
Labels: maintenance

#1648 LVGL / FS : Initialize the LVGL FS driver in LittleVgl (instead of FS).
  src/components/fs/FS.cpp
  src/components/fs/FS.h
  src/displayapp/DisplayApp.cpp
  src/displayapp/LittleVgl.cpp
  src/displayapp/LittleVgl.h
Labels: bug

#1649 README: Remove status badge
  README.md
Labels: documentation
