Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2023-08, with the labels that each got.

#1825 [docs] Include repository initialization in docker build doc
  doc/buildWithDocker.md
Labels: documentation

#1824 background for analog watch face in lvgl
  src/CMakeLists.txt
  src/displayapp/icons/bg_clock.c
  src/displayapp/screens/WatchFaceAnalog.cpp
  src/displayapp/screens/WatchFaceAnalog.h
Labels: maintenance, UI/UX

#827 Implement Lower to Sleep functionality
  src/components/motion/MotionController.cpp
  src/components/motion/MotionController.h
  src/components/settings/Settings.h
  src/displayapp/screens/settings/SettingWakeUp.cpp
  src/displayapp/screens/settings/SettingWakeUp.h
  src/systemtask/SystemTask.cpp
Labels: new feature
