Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2023-01, with the labels that each got.

#1510 SetingTimeFormat use CheckboxList, reduce duplication
  src/displayapp/screens/CheckboxList.cpp
  src/displayapp/screens/settings/SettingTimeFormat.cpp
  src/displayapp/screens/settings/SettingTimeFormat.h
Labels: maintenance

#1504 Update workflow dependencies
  .github/workflows/docker.yml
  .github/workflows/main.yml
Labels: maintenance

#1505 Gray settings list
  src/displayapp/screens/List.cpp
Labels: enhancement

#1545 minor grammar edit
  README.md
Labels: documentation

#1546 minor grammar edits
  doc/gettingStarted/gettingStarted-1.0.md
Labels: documentation

#1549 Update contribute guide
  doc/contribute.md
Labels: documentation

#1543 Fix Apps documentation DisplayApp method name
  doc/code/Apps.md
Labels: documentation

#1501 Enable unused parameter warning. Fix warnings.
  CMakeLists.txt
  src/CMakeLists.txt
  src/components/ble/AlertNotificationClient.cpp
  src/components/ble/AlertNotificationClient.h
  src/components/ble/AlertNotificationService.cpp
  src/components/ble/AlertNotificationService.h
  src/components/ble/BatteryInformationService.cpp
  src/components/ble/BatteryInformationService.h
  src/components/ble/CurrentTimeClient.cpp
  src/components/ble/CurrentTimeService.cpp
  src/components/ble/CurrentTimeService.h
  src/components/ble/DeviceInformationService.cpp
  src/components/ble/DeviceInformationService.h
  src/components/ble/HeartRateService.cpp
  src/components/ble/HeartRateService.h
  src/components/ble/ImmediateAlertService.cpp
  src/components/ble/ImmediateAlertService.h
  src/components/ble/MotionService.cpp
  src/components/ble/MotionService.h
  src/components/ble/MusicService.cpp
  src/components/ble/MusicService.h
  src/components/ble/NavigationService.cpp
  src/components/ble/NavigationService.h
  src/components/ble/NimbleController.cpp
  src/components/ble/weather/WeatherService.cpp
  src/components/ble/weather/WeatherService.h
  src/components/datetime/DateTimeController.cpp
  src/components/datetime/DateTimeController.h
  src/components/fs/FS.cpp
  src/components/motor/MotorController.cpp
  src/displayapp/DisplayAppRecovery.cpp
  src/displayapp/screens/Paddle.cpp
  src/displayapp/screens/Screen.h
  src/displayapp/screens/settings/SettingBluetooth.cpp
  src/displayapp/screens/settings/SettingBluetooth.h
  src/displayapp/screens/settings/SettingSetDate.cpp
  src/displayapp/screens/settings/SettingSetTime.cpp
  src/drivers/Bma421.cpp
  src/drivers/DebugPins.h
  src/drivers/SpiMaster.cpp
  src/drivers/SpiMaster.h
  src/recoveryLoader.cpp
Labels: maintenance

#1567 build-size-workflow: Fix when base gets updated
  .github/workflows/main.yml
Labels: bug

#1572 Revert "Comment build size on all PRs"
  .github/workflows/main.yml
  .github/workflows/pr-comment.yml
Labels: bug

#1574 workflow: Buildsize comment when simulator fails
  .github/workflows/pr-comment.yml
Labels: bug
