Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2024-11, with the labels that each got.

#1782 Update Date&Time settings label for "Date & Time"
  src/displayapp/screens/settings/Settings.h
Labels: UI/UX

#2166 ci: Normalise slash-containing `github.head_ref` values
  .github/workflows/main.yml
Labels: bug, maintenance

#1935 Fix git hash calculation with Docker build
  docker/Dockerfile
Labels: bug
