Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2024-02, with the labels that each got.

#2011 SimpleWeatherService: Add forecast operator overrides
  src/components/ble/SimpleWeatherService.cpp
  src/components/ble/SimpleWeatherService.h
Labels: weather

#1998 WatchFaceDigital: Move weather widget away from status icons
  src/displayapp/screens/WatchFaceDigital.cpp
Labels: UI/UX

#1950 Change Acceleration Values to milli-g units rather than Raw Counts
  doc/MotionService.md
  src/displayapp/screens/Motion.cpp
  src/drivers/Bma421.cpp
  src/drivers/Bma421.h
Labels: maintenance

#1996 Alarm: Replace clock icon with bell
  src/displayapp/fonts/fonts.json
  src/displayapp/screens/Alarm.h
  src/displayapp/screens/Symbols.h
Labels: UI/UX

#1993 README: Make hex and UTF-8 code consistent for the chosen example
  src/displayapp/fonts/README.md
Labels: documentation

#2025 README: Fix broken URLs
  README.md
  bootloader/ota-dfu-python/README.md
  src/drivers/Hrs3300.cpp
Labels: documentation
