Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2024-01, with the labels that each got.

#1943 docs: Fix simple weather forecast message type
  doc/SimpleWeatherService.md
Labels: documentation

#1952 apps: restore default apps ordering in CMake
  src/displayapp/apps/CMakeLists.txt
Labels: UI/UX

#1511 Update pre-commit hook
  hooks/pre-commit
Labels: maintenance

#1989 lv_img_conv: support other modes like 'P'
  src/resources/lv_img_conv.py
Labels: feature request

#1326 New dice-rolling app: InfiniDice!
  src/CMakeLists.txt
  src/displayapp/DisplayApp.cpp
  src/displayapp/UserApps.h
  src/displayapp/apps/Apps.h.in
  src/displayapp/apps/CMakeLists.txt
  src/displayapp/fonts/fonts.json
  src/displayapp/screens/Dice.cpp
  src/displayapp/screens/Dice.h
  src/displayapp/screens/Symbols.h
Labels: new app

#1970 Fix motion service not updating when sleeping
  src/components/ble/MotionService.cpp
  src/components/ble/MotionService.h
  src/components/motion/MotionController.h
  src/systemtask/SystemTask.cpp
Labels: bug
