Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2025-05, with the labels that each got.

#1483 Simple calculator
  src/CMakeLists.txt
  src/displayapp/DisplayApp.cpp
  src/displayapp/apps/Apps.h.in
  src/displayapp/apps/CMakeLists.txt
  src/displayapp/fonts/fonts.json
  src/displayapp/screens/Calculator.cpp
  src/displayapp/screens/Calculator.h
  src/displayapp/screens/Symbols.h
Labels: new app

#2237 Add background color to progress bar when flashing firmware
  src/displayapp/screens/FirmwareUpdate.cpp
Labels: enhancement, UI/UX

#1768 Remove the vibration while charging
  src/displayapp/DisplayApp.cpp
  src/displayapp/Messages.h
  src/systemtask/SystemTask.cpp
Labels: enhancement

#2229 Center text on timer button
  src/displayapp/screens/Timer.cpp
Labels: enhancement, maintenance

#2279 Fix about screen vertical centering.
  src/displayapp/screens/SystemInfo.cpp
Labels: UI/UX

#2282 Fixes the short ref not being set in Github builds
  .github/workflows/main.yml
Labels: maintenance

#1694 notification: Initialise message
  src/components/ble/NotificationManager.h
Labels: maintenance

#2270 Fix nrf sdk download links
  doc/buildAndProgram.md
  docker/build.sh
Labels: documentation, maintenance

#2299 docker: fix NRF_SDK download and subsequent build.sh
  docker/build.sh
Labels: bug

#2261 docker: fix libpango1.0-dev package name
  docker/Dockerfile
Labels: maintenance

#2300 DisplayApp: use std::ranges function where possible
  src/displayapp/DisplayApp.cpp
Labels: maintenance
