Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2025-02, with the labels that each got.

#2238 Notification -> Notifications
  src/displayapp/screens/Notifications.cpp
Labels: enhancement, UI/UX

#2077 Fix EOL related build issues on Windows
  .gitattributes
Labels: maintenance

#2256 Prevents blocking when Infineat watchface is charging
  src/displayapp/screens/WatchFaceInfineat.cpp
  src/displayapp/screens/WatchFaceInfineat.h
Labels: bug
