Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2025-03, with the labels that each got.

#2236 BatteryInfo App Redesign
  src/displayapp/screens/BatteryInfo.cpp
  src/displayapp/screens/BatteryInfo.h
Labels: enhancement, UI/UX

#2158 work around g++ version 12, 13 and 14 spurious warning
  src/displayapp/screens/SystemInfo.cpp
Labels: maintenance

#2152 Documentation: Minor fix to example app code
  doc/code/Apps.md
Labels: documentation
