Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2025-01, with the labels that each got.

#1884 Show alarm controller state in status icons
  src/displayapp/DisplayApp.cpp
  src/displayapp/screens/ApplicationList.cpp
  src/displayapp/screens/ApplicationList.h
  src/displayapp/screens/Tile.cpp
  src/displayapp/screens/Tile.h
  src/displayapp/screens/WatchFaceDigital.cpp
  src/displayapp/screens/WatchFaceDigital.h
  src/displayapp/screens/settings/QuickSettings.cpp
  src/displayapp/screens/settings/QuickSettings.h
  src/displayapp/widgets/StatusIcons.cpp
  src/displayapp/widgets/StatusIcons.h
Labels: enhancement

#2211 Alarm: Simplify alarm alerting screen (and fix bug with alerting on time value change)
  src/components/alarm/AlarmController.cpp
  src/displayapp/screens/Alarm.cpp
Labels: enhancement, UI/UX

#2224 CI: Use artifact v4 instead of v3
  .github/workflows/format.yml
  .github/workflows/main.yml
Labels: maintenance

#2150 Add "Run on InfiniEmu" link to pull requests, update actions/upload-artifact
  .github/workflows/main.yml
Labels: new feature
