Repository InfiniTimeOrg/InfiniTime, pull requests merged in 2025-06, with the labels that each got.

#2312 set static text as static text
  src/displayapp/screens/settings/SettingWakeUp.cpp
Labels: maintenance

#2181 Set LF-only (\n) line endings for .sh files to fix #1905
  .gitattributes
Labels: maintenance

#2313 Ignoring npm files
  .gitignore
Labels: maintenance

#2201 Pride flag watchface
  src/CMakeLists.txt
  src/components/datetime/DateTimeController.cpp
  src/components/datetime/DateTimeController.h
  src/components/settings/Settings.h
  src/displayapp/UserApps.h
  src/displayapp/apps/Apps.h.in
  src/displayapp/apps/CMakeLists.txt
  src/displayapp/screens/WatchFacePrideFlag.cpp
  src/displayapp/screens/WatchFacePrideFlag.h
Labels: new watchface

#2326 Disable legacy FreeRTOS functions
  src/FreeRTOSConfig.h
Labels: maintenance

#2331 Initialise DisplayApp components in DisplayApp context
  src/displayapp/DisplayApp.cpp
  src/displayapp/DisplayApp.h
Labels: maintenance

#2292 (small) Music App Redesign
  src/components/ble/MusicService.h
  src/displayapp/screens/Music.cpp
Labels: enhancement
